name: Update

on:
  push:
    branches:
      - master
  label:
    types:
      - created
  schedule:
    - cron: '30 10 * * 3' # 00:07 Beijing time (UTC+8), Wed

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create .env file 
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}" >> .env

      - name: Update papers
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '✏️ New Repos INCOMING'
          branch: master
          file_pattern: '*'

      - name: Create an issue to notify
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}